spring:
  datasource:
    url: 'jdbc:h2:mem:core;MODE=MYSQL;'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /service-docs.html
    query-config-enabled: true
    enabled: true
