spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
#      - monitoring.yml
      - logging.yml
#      - db-core.yml
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
