apiVersion: 1

deleteDatasources:
  - name: prometheus

datasources:
  - name: coupon-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: coupon-performance-influxdb
    type: influxdb
    access: proxy
    database: k6
    user: admin
    password: admin1234
    url: http://influxdb:8086
