spring:
  datasource:
    url: jdbc:mysql://localhost:3306/couponDB
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # sprig boot 3.x
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    listener:
      ack-mode: manual
