spring:
  datasource:
    url: jdbc:mysql://localhost:3306/couponDB
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  kafka:
    listener:
      ack-mode: manual
      default-error-handler:
        recoverer:
          type: dead-letter
          dead-letter-topic-name: coupon_issue.DLT
        backoff:
          initialInterval: 10000
          maxAttempts: 5
