{
 "title": "Coupon Consumer Server - Dashboard",
 "tags": [
  "coupon-consumer-server",
  "kafka",
  "performance"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(jvm_memory_used_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Listener Processed Count (Individual & Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Messages / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_kafka_listener_seconds_count{instance=~\"$instance\"}[1m])) by (listener_id, instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(spring_kafka_listener_seconds_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Total TPS"
    }
   ]
  },
  {
   "title": "Consumer Lag Count (Issue Topic)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"coupon-issue\"})",
     "legendFormat": "Issue Lag"
    }
   ]
  },
  {
   "title": "Consumer Lag Count (DLQ Topic)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"coupon-issue-dlq\"})",
     "legendFormat": "DLQ Lag"
    }
   ]
  },
  {
   "title": "Kafka Listener Error Rate [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Error Rate (%)" }
   ],
   "targets": [
    {
     "expr": "100 * (sum(rate(spring_kafka_listener_seconds_count{instance=~\"$instance\", result=\"failure\"}[1m])) or vector(0)) / (sum(rate(spring_kafka_listener_seconds_count{instance=~\"$instance\"}[1m])) or vector(1))",
     "legendFormat": "{{listener_id}} - Error Rate"
    }
   ]
  },
  {
   "title": "Listener Processing Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(spring_kafka_listener_seconds_sum{instance=~\"$instance\"}[1m])) by (listener_id) / sum(rate(spring_kafka_listener_seconds_count{instance=~\"$instance\"}[1m])) by (listener_id)) * 1000",
     "legendFormat": "{{listener_id}} Avg Time (ms)"
    }
   ]
  },
  {
   "title": "Listener Processing Time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_max{instance=~\"$instance\"} * 1000",
     "legendFormat": "{{listener_id}} Max Time (ms)"
    }
   ]
  },
  {
   "title": "DB Active Connections [Count]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} Active"
    }
   ]
  },
  {
   "title": "DB Pending Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_pending{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} Pending"
    }
   ]
  },
  {
   "title": "CPU Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage (%)" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\"} * 100",
     "legendFormat": "System"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"} * 100",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "JVM Heap Memory [MB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "mbytes", "label": "Memory (MB)" }
   ],
   "targets": [
    {
     "expr": "sum without (id) (jvm_memory_used_bytes{area=\"heap\", instance=~\"$instance\"}) / (1024*1024)",
     "legendFormat": "{{instance}} Heap Used"
    },
    {
     "expr": "sum without (id) (jvm_memory_max_bytes{area=\"heap\", instance=~\"$instance\"}) / (1024*1024)",
     "legendFormat": "{{instance}} Heap Max"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{instance=~\"$instance\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GC Duration (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=~\"$instance\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=~\"$instance\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Threads Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=~\"$instance\", state=~\"runnable|blocked|waiting|timed_waiting\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Rebalance Rate [Count]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(delta(kafka_consumergroup_group_rebalances_total{group=\"coupon-issue-group\"}[1m])) or vector(0))",
     "legendFormat": "Rebalances"
    }
   ]
  },
  {
   "title": "Time Between Poll [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_time_between_poll_avg) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Avg Records Per Request [Count]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_records_per_request_avg) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}