{
 "title": "Coupon Consumer - Dashboard",
 "tags": [
  "coupon-consumer-server",
  "performance"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Listener Processed Count (operations per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Messages / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_kafka_listener_seconds_count{instance=\"host.docker.internal:8083\"}[1m])) by (listener_id)",
     "legendFormat": "{{listener_id}} Processed Count"
    }
   ]
  },
  {
   "title": "Kafka Listener Processing Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(spring_kafka_listener_seconds_sum{instance=\"host.docker.internal:8083\"}[1m])) by (listener_id) / sum(rate(spring_kafka_listener_seconds_count{instance=\"host.docker.internal:8083\"}[1m])) by (listener_id)) * 1000",
     "legendFormat": "{{listener_id}} Avg Processing Time"
    }
   ]
  },
  {
   "title": "Kafka Listener Max Processing Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Time (ms)" }
   ],
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_max{instance=\"host.docker.internal:8083\"} * 1000",
     "legendFormat": "{{listener_id}} Max Processing Time"
    }
   ]
  },
  {
   "title": "Kafka Consumer Process CPU Usage (%) - PORT: 8083",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage (%)" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"host.docker.internal:8083\"} * 100",
     "legendFormat": "{{instance}} - CPU Usage"
    }
   ]
  },
  {
   "title": "Kafka Consumer JVM Heap Memory (MB) - PORT: 8083",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "mbytes", "label": "Memory (MB)" }
   ],
   "targets": [
    {
     "expr": "sum without (id) (jvm_memory_used_bytes{area=\"heap\", instance=\"host.docker.internal:8083\"}) / (1024*1024)",
     "legendFormat": "{{instance}} Heap Used (MB)"
    },
    {
     "expr": "sum without (id) (jvm_memory_max_bytes{area=\"heap\", instance=\"host.docker.internal:8083\"}) / (1024*1024)",
     "legendFormat": "{{instance}} Heap Max (MB)"
    }
   ]
  },
  {
   "title": "Kafka Listener Error Rate (%) - PORT: 8083",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Error Rate (%)" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(spring_kafka_listener_seconds_count{instance=\"host.docker.internal:8083\", result=\"failure\"}[1m])) by (listener_id) / sum(rate(spring_kafka_listener_seconds_count{instance=\"host.docker.internal:8083\"}[1m])) by (listener_id)",
     "legendFormat": "{{listener_id}} - Error Rate"
    }
   ]
  },
  {
   "title": "Kafka Consumer Max Lag (coupon_issue)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag_max{group=\"group_1\", topic=\"coupon_issue\"})",
     "legendFormat": "Max Lag"
    }
   ]
  },
  {
   "title": "DB Active Connections (HikariCP) - PORT: 8083",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"host.docker.internal:8083\"}",
     "legendFormat": "{{pool}} Active"
    }
   ]
  },
  {
   "title": "DB Pending Connections (HikariCP) - PORT: 8083",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_pending{instance=\"host.docker.internal:8083\"}",
     "legendFormat": "{{pool}} Pending"
    }
   ]
  }
 ]
}